name: Trigger Doc Update
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README_EN.md"
      - "README.md"

jobs:
  trigger-Doc-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger update
        run: |
          curl -X POST https://api.github.com/repos/pot-app/pot-docs/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -d '{"event_type": "plugins-updated"}'
